site_name: HSR Notizen
site_url: https://doc.robinsuter.ch
repo_url: https://github.com/Excape/hsr-docs-hs16
site_description: HSR Study Documentation HS16
site_author: Robin Suter
copyright: 'Copyright (c) 2016 Robin Suter'

theme: 'material'
theme_dir: 'mkdocs-material/material'

pages:
  - Home: 'index.md'
  - HS16:
    - AD2: 'hs16/ad2.md'
    - BuRe1:
        - ReIng: 'hs16/reing.md'
        - BuPl: 'hs16/bupl.md'
    - C++: 
        - Notes: 'hs16/cpl.md'
        - Code: 'hs16/cpl_code.md'
    - EnglHTw: 'hs16/englhtw.md'
    - MGE: 
        - Notes: 'hs16/mge.md'
        - Summary Android: 'hs16/mge_summary_android.md'
        - Summary WPF: 'hs16/mge_summary_wpf.md'
    - MsTe: 'hs16/mste.md'
    - SE1: 'hs16/se1.md'
    - WED2: 'hs16/wed2.md'
  - Playground: 'playground.md'



markdown_extensions:
  - toc
  - sane_lists
  - admonition
  - mdx_math
  - codehilite
  

extra:
    palette:
        primary: 'red'
        accent: 'amber'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    author:
        github: 'excape'
        twitter: 'robin_suter'

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_SVG

extra_css: [extra.css]
